2021-09-14 22:46:40,951 INFO    MainThread:5619 [internal.py:wandb_internal():89] W&B internal server running at pid: 5619, started at: 2021-09-14 22:46:40.951492
2021-09-14 22:46:40,955 DEBUG   HandlerThread:5619 [handler.py:handle_request():126] handle_request: run_start
2021-09-14 22:46:40,956 INFO    WriterThread:5619 [datastore.py:open_for_write():77] open: /home/osselinp/teachDeepRL/wandb/offline-run-20210914_224640-1auswxlq/run-1auswxlq.wandb
2021-09-14 22:46:42,518 DEBUG   HandlerThread:5619 [meta.py:__init__():40] meta init
2021-09-14 22:46:42,519 DEBUG   HandlerThread:5619 [meta.py:__init__():54] meta init done
2021-09-14 22:46:42,519 DEBUG   HandlerThread:5619 [meta.py:probe():211] probe
2021-09-14 22:46:42,526 DEBUG   HandlerThread:5619 [meta.py:_setup_git():201] setup git
2021-09-14 22:46:42,558 DEBUG   HandlerThread:5619 [meta.py:_setup_git():208] setup git done
2021-09-14 22:46:42,559 DEBUG   HandlerThread:5619 [meta.py:_save_pip():58] save pip
2021-09-14 22:46:42,559 DEBUG   HandlerThread:5619 [meta.py:_save_pip():72] save pip done
2021-09-14 22:46:42,560 DEBUG   HandlerThread:5619 [meta.py:_save_conda():79] save conda
2021-09-14 22:46:45,129 DEBUG   HandlerThread:5619 [meta.py:_save_conda():87] save conda done
2021-09-14 22:46:45,129 DEBUG   HandlerThread:5619 [meta.py:probe():249] probe done
2021-09-14 22:54:19,763 WARNING MainThread:5619 [internal.py:wandb_internal():145] Internal process interrupt: 1
2021-09-14 22:54:19,865 WARNING MainThread:5619 [internal.py:wandb_internal():145] Internal process interrupt: 2
2021-09-14 22:54:19,865 ERROR   MainThread:5619 [internal.py:wandb_internal():148] Internal process interrupted.
2021-09-14 22:54:20,084 INFO    SenderThread:5619 [sender.py:finish():979] shutting down sender
2021-09-14 22:54:20,437 INFO    WriterThread:5619 [datastore.py:close():281] close: /home/osselinp/teachDeepRL/wandb/offline-run-20210914_224640-1auswxlq/run-1auswxlq.wandb
2021-09-14 22:54:20,463 INFO    HandlerThread:5619 [handler.py:finish():683] shutting down handler
2021-09-14 22:54:20,466 INFO    MainThread:5619 [internal.py:handle_exit():76] Internal process exited
